defaults:
  - scope:
      path: ''
    values:
      layout: default

exclude:
  - CHANGELOG.md
  - docker-compose.yaml
  - LICENSE
  - makefile
  - package.json
  - package-lock.json
  - postcss.config.js
  - README.md
  - tailwind.config.js

title: JHAE GitHub Page Template

# -> GitHub metadata plugin
repository: jhae-de/github-page-template
# <- GitHub metadata plugin

# -> Remote theme plugin
remote_theme: jhae-de/github-page-theme@7d2d3acf5b89f58743b492ebdb1e340acb67b291
# <- Remote theme plugin
