defaults:
  - scope:
      path: ''
    values:
      layout: default

title: JHAE GitHub Page Template

# -> GitHub metadata plugin
repository: jhae-de/github-page-template
# <- GitHub metadata plugin

# -> Remote theme plugin
remote_theme: jhae-de/github-page-theme@1e90372d076d399e4d332ddd91a4ca177110ef85
# <- Remote theme plugin
