defaults:
  - scope:
      path: ""
    values:
      layout: default

remote_theme: jhae-de/github-page-theme@a757e28b2fe040e549958c4eb22c4125032146e5

repository: jhae-de/github-page-template

title: JHAE GitHub Page Template
