defaults:
  - scope:
      path: ''
    values:
      layout: default

exclude:
  - /assets/scripts/*.ts
  - /assets/scripts/**/*.ts
  - /bin
  - /coverage
  - /build-scripts.ts
  - /CHANGELOG.md
  - /codecov.yaml
  - /docker-compose.yaml
  - /eslint.config.js
  - /jest.config.js
  - /LICENSE
  - /makefile
  - /package.json
  - /package-lock.json
  - /postcss.config.ts
  - /README.md
  - /tailwind.*.ts
  - /tsconfig.json

postcss:
  config: postcss.config.ts

sass:
  quiet_deps: true

title: JHAE GitHub Page Template

# GitHub metadata plugin options
repository: jhae-de/github-page-template
