name: Publish (Test)
run-name: Test release ${{ github.ref_name }}

on:
  release:
    types:
      - published

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: feature/initial-release

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.191.0
        with:
          ruby-version: "3.2"
          bundler-cache: true
          cache-version: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm clean-install

      - name: Configure page
        id: configure-page
        uses: actions/configure-pages@v5

      - name: Build page
        run: bundle exec jekyll build --baseurl "${{ steps.configure-page.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: Upload page artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deploy-page.outputs.page_url }}

    steps:
      - name: Deploy page
        id: deploy-page
        uses: actions/deploy-pages@v4
